--liquibase formatted sql

--changeset shokhrukh:0001-create-users-table

CREATE TABLE users
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name VARCHAR NOT NULL,
    last_name  VARCHAR NOT NULL,
    username   VARCHAR NOT NULL,
    password   VARCHAR NOT NULL,
    birth_date DATE    NOT NULL,
    enabled    BOOLEAN NOT NULL
);

--rollback DROP TABLE IF EXISTS users CASCADE;