--liquibase formatted sql

--changeset shokhrukh:0001-create-users-table

CREATE TABLE users
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    firstname VARCHAR NOT NULL,
    lastname  VARCHAR NOT NULL,
    username  VARCHAR NOT NULL,
    password  VARCHAR NOT NULL,
    birthdate DATE    NOT NULL
);

--rollback DROP TABLE IF EXISTS users CASCADE;