--liquibase formatted sql

--changeset shokhrukh:0001-create-test-table

CREATE TABLE test
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY
);

--rollback DROP TABLE IF EXISTS test CASCADE;