--liquibase formatted sql

--changeset shokhrukh:0002-create-roles-table

CREATE TABLE roles
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR NOT NULL
);

--rollback DROP TABLE IF EXISTS roles CASCADE;