spring:
  application:
    name: socials
  main:
    banner-mode: off
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}?currentSchema=${POSTGRES_SCHEMA}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}

management:
  endpoints:
    web:
      exposure:
        include: health
      base-path: /status

springdoc:
  api-docs:
    path: /docs/v1/api-docs
  swagger-ui:
    path: /docs/v1/swagger-ui.html
    doc-expansion: none
    tags-sorter: alpha
    default-model-expand-depth: -1
    default-models-expand-depth: -1

app:
  white-list:
    - /error
    - /actuator/health
    - /docs/**
    - /api/v1/auth/sign-in
    - /api/v1/auth/sign-up
  jwt:
    secret: ${APP_JWT_SECRET}
    expiration: ${APP_JWT_EXPIRATION}

#logging:
#  level:
#    com.devcamp.socials: DEBUG

server:
  port: ${SERVER_PORT:8080}

